### PR TITLE
Fix up mli to conform to ocamldoc levels (avoiding 0)

### PR DESCRIPTION
**Pull request by bluddy**
The structure of the `ldap_ooclient.mli` file completely messes up odoc. This attempts to fix it. Let me know if any of these changes seems off.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks a lot! Do you require me to make a release or is it fine for the moment?

**Comment by bluddy** [comment]
I'm debugging another issue in odoc generation for ldap, so no need to release yet.

**Comment by bluddy** [comment]
On second thought, if you could make a release, I could easily point the `odoc` folks to a really weird memory leak I get after getting past this issue. Would that be ok? Sorry to bother you.

**Comment by kit-ty-kate** [comment]
I'm really sorry for the time it took but it's now merged in opam-repository

**Pull request merged**
